# Generated by Django 4.2.4 on 2024-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'categoriaCultivo',
                'verbose_name_plural': 'categoriasCultivos',
                'db_table': 'categoriaCultivo',
            },
        ),
    ]
