# Generated by Django 5.0.4 on 2024-05-03 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=45, verbose_name='Pedido')),
                ('nombre', models.CharField(max_length=45, verbose_name='Descripción')),
                ('imagen', models.CharField(max_length=45)),
                ('direccion_envio', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=8)),
                ('favoritos', models.CharField(max_length=45, verbose_name='Favoritos')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.IntegerField(primary_key=True, serialize=False)),
                ('productos', models.CharField(max_length=45, verbose_name='Productos')),
                ('pedido_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_web.pedido')),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripción')),
                ('imagen', models.CharField(max_length=45)),
                ('stock', models.CharField(max_length=45)),
                ('producto_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_web.pedido')),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_web.productos')),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_web.usuario'),
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('idcultivo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripción')),
                ('imagen', models.CharField(max_length=45)),
                ('region', models.CharField(max_length=45)),
                ('estacion_siembra', models.CharField(max_length=45)),
                ('usuario_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_web.usuario')),
            ],
            options={
                'db_table': 'Cultivo',
            },
        ),
    ]
