# Generated by Django 5.0.4 on 2024-05-08 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id_cultivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=45)),
                ('estacion_de_siembra', models.CharField(max_length=45)),
                ('temperatura_recomendada', models.FloatField()),
                ('favorito', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
