# Generated by Django 5.0.4 on 2024-05-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='categoria',
            field=models.CharField(default='vegetal', max_length=45),
            preserve_default=False,
        ),
    ]
