# Generated by Django 5.0.4 on 2024-05-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_cultivo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
