# Generated by Django 4.2.4 on 2024-05-19 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripción')),
                ('imagen', models.CharField(max_length=45)),
                ('stock', models.CharField(max_length=45)),
                ('producto_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=45, verbose_name='Pedido')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripción')),
                ('imagen', models.CharField(max_length=45)),
                ('direccion_envio', models.CharField(max_length=45)),
                ('pedido_generado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_web.productos')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_web.productos')),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.IntegerField(primary_key=True, serialize=False)),
                ('productos', models.CharField(max_length=45, verbose_name='Productos')),
                ('pedido_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion_web.pedido')),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
    ]
