# Generated by Django 5.0.4 on 2024-05-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='favoritos',
            field=models.CharField(max_length=45),
        ),
    ]
